apiVersion: apps/v1
kind: Deployment
metadata:
  name: invo-deployment
  labels:
    app: invo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: invo
  template:
    metadata:
      labels:
        app: invo
    spec:
      containers:
      - name: invo
        image: invo:8.1
        ports:
        - containerPort: 80
