name: Deploy Invo 8.1 to EKS

on: workflow_dispatch

jobs:
    deploy:
        name: Deploy to EKS
        runs-on: ubuntu-latest

        steps:

            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-2

            - name: kubectl-simple
              uses: steebchen/kubectl@v2.1.1
              with:
                command: apply -f k8s/deployment.yml
                config: ${{ secrets.KUBECONFIG }}
