name: Docker Build

on: workflow_dispatch

jobs:
    docker:
        name: Build Invo 8.1 Docker Image
        runs-on: ubuntu-latest

        steps:

            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Docker Login
              uses: docker/login-action@v3.1.0
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and push Docker images
              uses: docker/build-push-action@v5.3.0
              with:
                context: docker/8.1/
                push: true
                tags: hfoster/invo:8.1, hfoster/invo:latest
